# Generated by Django 3.0.7 on 2020-08-12 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('minitems', models.IntegerField()),
                ('maxitems', models.IntegerField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Categoriaproducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('capital', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='direccionusuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barrio', models.CharField(max_length=20)),
                ('direccion', models.TextField(max_length=40)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Ciudad', to_field='nombre')),
                ('usuario', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='estadopedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='payudata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(blank=True, max_length=250)),
                ('merchantid', models.IntegerField()),
                ('accountId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tienda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('imagen', models.ImageField(upload_to='')),
                ('barrio', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('direccion', models.TextField(max_length=40)),
                ('Numeroitems', models.IntegerField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Categoria', to_field='nombre')),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Ciudad', to_field='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tiendacustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fondo', models.ImageField(null=True, upload_to='fondos')),
                ('tienda', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.tienda', to_field='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('imagen', models.ImageField(upload_to='media')),
                ('precio', models.IntegerField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Categoriaproducto', to_field='nombre')),
                ('tiendaid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.tienda', to_field='nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('direccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.direccionusuario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('rate', models.IntegerField(default=1)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Verdadero', 'Verdadero'), ('Falso', 'Falso')], default='Nuevo', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tienda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carritodecompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('estadoproducto', models.ForeignKey(blank=True, default='Por confirmar', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.estadopedido', to_field='nombre')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Pedido')),
                ('productoid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Product')),
            ],
        ),
    ]
