# Generated by Django 3.0.7 on 2020-08-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
