# Generated by Django 3.0.7 on 2020-08-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pedido_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
    ]
