# Generated by Django 3.0.7 on 2020-08-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_product_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
