# Generated by Django 3.0.7 on 2020-08-23 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200822_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritodecompra',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.tienda'),
        ),
    ]
