# Generated by Django 3.0.7 on 2020-09-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200903_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionusuario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
