# Generated by Django 3.0.7 on 2020-09-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200904_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
