# Generated by Django 3.0.7 on 2020-09-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20200906_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.IntegerField(),
        ),
    ]
